let DATA, EVIDENCE=JSON.parse(localStorage.getItem("skasEvidenceV6")||localStorage.getItem("skasEvidenceV4")||"[]");
const DB_NAME="SKASDigitalDB", DB_VER=1, STORE="files";
const $=s=>document.querySelector(s), esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "'":"&#039;"}[c]));
const escA=s=>esc(s).replace(/`/g,"&#096;");
const icons={Dokumen:"📄",Gambar:"🖼️",Video:"🎬",Data:"📊","Lain-lain":"📎"};
let db;
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VER);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function putFile(obj){return new Promise((res,rej)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).put(obj);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function getFile(id){return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})}
function deleteFile(id){return new Promise((res,rej)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function allTargets(){const a=[];DATA.standards.forEach(s=>{if(s.direct)a.push({id:s.code,name:s.name,path:s.code});(s.aspects||[]).forEach(x=>{const hasItems=(x.items||[]).length>0, hasSubs=(x.subaspects||[]).length>0; if(!hasItems&&!hasSubs)a.push({id:x.code,name:x.name,path:`${s.code} › ${x.code} ${x.name}`}); (x.items||[]).forEach(i=>a.push({id:i[0],name:i[1],path:`${s.code} › ${x.code} ${x.name}`}));(x.subaspects||[]).forEach(sa=>(sa.items||[]).forEach(i=>a.push({id:i[0],name:i[1],path:`${s.code} › ${x.code} ${x.name} › ${sa.code} ${sa.name}`})))})});return a}
function targetIds(e){return e.targetIds||[e.targetId]}
function evidenceFor(id){return EVIDENCE.filter(e=>targetIds(e).includes(id))}
async function init(){await openDB();DATA=await fetch("data/instrument.json").then(r=>r.json());$("#school").textContent=DATA.school;buildNav();renderHome();fillTarget()}
function buildNav(){let n=$("#nav");DATA.standards.forEach(s=>{let b=document.createElement("button");b.className="nav-btn";b.innerHTML=`<span>${s.code} · ${esc(s.name)}</span><b>›</b>`;b.onclick=()=>openStandard(s.code);n.appendChild(b)});$(".home").onclick=()=>show("home")}
function show(v){$("#homeView").classList.toggle("hidden",v!=="home");$("#detailView").classList.toggle("hidden",v!=="detail");$("#resultsView").classList.toggle("hidden",v!=="results");document.querySelectorAll(".home,.nav-btn").forEach(x=>x.classList.remove("active"));if(v==="home")$(".home").classList.add("active");window.scrollTo({top:0,behavior:"smooth"})}
function renderHome(){
 $("#count").textContent=EVIDENCE.length;const targets=allTargets(),covered=new Set(EVIDENCE.flatMap(targetIds)).size;
 $("#stats").innerHTML=[["Jumlah eviden",EVIDENCE.length],["Pecahan sudah ada eviden",covered],["Pecahan belum ada eviden",Math.max(0,targets.length-covered)]].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join("");
 $("#progress").innerHTML=DATA.standards.map(s=>{const ts=targets.filter(t=>t.path.startsWith(s.code+" ")||t.id===s.code);const have=new Set(EVIDENCE.flatMap(targetIds).filter(id=>ts.some(t=>t.id===id))).size;const pct=ts.length?Math.round(have/ts.length*100):0;return `<div class="progress"><div class="progress-head"><span>${s.code} · ${esc(s.name)}</span><b>${pct}%</b></div><div class="bar"><div class="fill" style="width:${pct}%"></div></div></div>`}).join("");
 const rec=[...EVIDENCE].sort((a,b)=>(b.date||"").localeCompare(a.date||"")).slice(0,8);$("#recent").innerHTML=rec.length?rec.map(e=>recentHtml(e)).join(""):`<div class="muted">Belum ada eviden. Gunakan butang “Tambah Eviden” untuk mula.</div>`;
}
function recentHtml(e){return `<div class="recent"><div class="ico">${icons[e.category]||"📎"}</div><div><strong>${esc(e.title)}</strong><small>${esc((e.targetLabel||targetIds(e).join(", ")))} ${e.date?"• "+e.date:""}</small></div></div>`}
function openStandard(code){const s=DATA.standards.find(x=>x.code===code);if(!s)return;let body="";
 if(s.direct){body=`<div class="direct"><span class="tag">${s.code}</span><h2>${esc(s.name)}</h2><p class="muted">Eviden boleh direkodkan terus pada Standard 4.0. Pecahan dalaman tidak diberikan dalam struktur yang dibekalkan.</p><div class="item"><div class="item-text">📁 Eviden Standard 4.0</div><div><span class="evidence-count">${evidenceFor(s.code).length} eviden</span> <button class="add-mini" onclick="addFor('${s.code}','${escA(s.name)}')">+ Eviden</button></div></div><div class="evidence-list">${renderEvidence(s.code)}</div></div>`;
 }else body=(s.aspects||[]).map(a=>{const hasItems=(a.items||[]).length>0, hasSubs=(a.subaspects||[]).length>0; if(!hasItems&&!hasSubs){const cnt=evidenceFor(a.code).length;return `<div class="aspect-card"><div class="aspect-head"><div><b>${a.code} · ${esc(a.name)}</b><small style="display:block;margin-top:4px">Aspek</small></div><div><span class="evidence-count">${cnt} eviden</span> <button class="add-mini" onclick="addFor('${escA(a.code)}','${escA(a.name)}')">+ Eviden</button></div></div>${cnt?`<div class="evidence-list compact">${renderEvidence(a.code)}</div>`:""}</div>`} let items=(a.items||[]).map(i=>itemHtml(i)).join("");if(a.subaspects)items=a.subaspects.map(sa=>`<div class="aspect-card"><div class="aspect-head"><b>${sa.code} · ${esc(sa.name)}</b><small>${sa.items.length} pecahan</small></div>${sa.items.map(i=>itemHtml(i)).join("")}</div>`).join("");return `<div class="aspect-card"><div class="aspect-head"><b>${a.code} · ${esc(a.name)}</b><small>${a.subaspects?a.subaspects.length+" bahagian":(a.items||[]).length+" pecahan"}</small></div>${items}</div>`}).join("");
 $("#detail").innerHTML=`<div class="title"><div><span>${s.code}</span><h2>${esc(s.name)}</h2></div></div>${body}`;show("detail")}
function itemHtml(i){const id=i[0],cnt=evidenceFor(id).length;return `<div class="item"><div class="item-text"><span class="item-code">${id}</span>${esc(i[1])}</div><div><span class="evidence-count">${cnt} eviden</span> <button class="add-mini" onclick="addFor('${escA(id)}','${escA(i[1])}')">+ Eviden</button></div></div>${cnt?`<div class="evidence-list compact">${renderEvidence(id)}</div>`:""}`}
function renderEvidence(id){const ev=evidenceFor(id);return ev.length?ev.map(e=>`<div class="evidence-row"><strong>${icons[e.category]||"📎"} ${esc(e.title)}</strong><small>${esc(e.owner||"Tiada pemilik")} ${e.date?"• "+e.date:""}${targetIds(e).length>1?` • ${targetIds(e).length} pecahan`:""}${e.note?" • "+esc(e.note):""}</small>${e.fileId?`<button class="link-btn" onclick="previewFile('${escA(e.fileId)}')">Buka fail ↗</button>`:""}${e.url?` <a href="${escA(e.url)}" target="_blank" rel="noopener">Buka pautan ↗</a>`:""}<button class="danger-link" onclick="removeEvidence('${escA(e.id)}')">Padam</button></div>`).join(""):`<div class="muted">Belum ada eviden untuk pecahan ini.</div>`}
function fillTarget(){const opts=allTargets();$("#target").innerHTML=opts.map(t=>`<option value="${escA(t.id)}">${esc(t.id)} — ${esc(t.name)}</option>`).join("")}
function fillMulti(selected=[]){const box=$("#targets");box.innerHTML=allTargets().map(t=>`<label class="check"><input type="checkbox" value="${escA(t.id)}" ${selected.includes(t.id)?"checked":""}> <span>${esc(t.id)} — ${esc(t.name)}</span></label>`).join("")}
function addFor(id,label){openModal(id,label)}
function openModal(id="",label=""){$("#modal").classList.remove("hidden");$("#form").reset();fillMulti(id?[id]:[]);$("#modal").dataset.targetLabel=label||"";$("#fileInfo").textContent="Tiada fail dipilih."}
function closeModal(){$("#modal").classList.add("hidden")}
$("#addBtn").onclick=()=>openModal();$("#close").onclick=closeModal;$("#cancel").onclick=closeModal;$("#file").onchange=e=>{$("#fileInfo").textContent=e.target.files[0]?`${e.target.files[0].name} • ${formatBytes(e.target.files[0].size)}`:"Tiada fail dipilih."};
$("#form").onsubmit=async e=>{e.preventDefault();const f=e.target,targets=[...f.querySelectorAll('#targets input:checked')].map(x=>x.value);if(!targets.length){alert("Pilih sekurang-kurangnya satu pecahan instrumen.");return}const file=f.file.files[0];let fileId="";if(file){fileId="f_"+Date.now()+"_"+Math.random().toString(36).slice(2);await putFile({id:fileId,name:file.name,type:file.type,size:file.size,blob:file})}const labels=targets.map(id=>allTargets().find(t=>t.id===id)).filter(Boolean);const ev={id:Date.now().toString(),targetIds:targets,targetLabel:labels.map(x=>x.id).join(", "),title:f.title.value.trim(),category:f.category.value,owner:f.owner.value.trim(),date:f.date.value,url:f.url.value.trim(),note:f.note.value.trim(),fileId};EVIDENCE.push(ev);localStorage.setItem("skasEvidenceV6",JSON.stringify(EVIDENCE));closeModal();renderHome();show("home")};
async function previewFile(id){const f=await getFile(id);if(!f){alert("Fail tidak ditemui dalam storan pelayar.");return}const url=URL.createObjectURL(f.blob);const win=window.open(url,"_blank");if(!win){alert("Pelayar menyekat tetingkap baharu. Benarkan pop-up untuk membuka fail.")}}
async function removeEvidence(id){const e=EVIDENCE.find(x=>x.id===id);if(!e)return;if(!confirm(`Padam eviden “${e.title}”?`))return;if(e.fileId)await deleteFile(e.fileId);EVIDENCE=EVIDENCE.filter(x=>x.id!==id);localStorage.setItem("skasEvidenceV6",JSON.stringify(EVIDENCE));renderHome();if(!$("#detailView").classList.contains("hidden")){const first=targetIds(e)[0];const s=DATA.standards.find(s=>s.code===first||first.startsWith(s.code+"."));if(s)openStandard(s.code);}}
function formatBytes(n){if(n<1024)return n+" B";if(n<1048576)return (n/1024).toFixed(1)+" KB";return (n/1048576).toFixed(1)+" MB"}
$("#back").onclick=()=>show("home");$("#clear").onclick=()=>{$("#search").value="";doSearch("")};$("#search").oninput=e=>doSearch(e.target.value);
function doSearch(q){q=q.trim().toLowerCase();if(!q){show("home");return}show("results");const targets=allTargets();const matches=targets.filter(t=>`${t.id} ${t.name} ${t.path}`.toLowerCase().includes(q));const ev=EVIDENCE.filter(e=>`${e.title} ${e.targetLabel} ${e.owner} ${e.note}`.toLowerCase().includes(q));let h="";matches.forEach(t=>h+=`<div class="result"><span class="tag">${esc(t.id)}</span><h3>${esc(t.name)}</h3><p>${esc(t.path)} • ${evidenceFor(t.id).length} eviden</p><button onclick="addFor('${escA(t.id)}','${escA(t.name)}')">+ Tambah eviden</button></div>`);ev.forEach(e=>h+=`<div class="result"><span class="tag">${esc(e.category)}</span><h3>${esc(e.title)}</h3><p>${esc(e.targetLabel)}${e.owner?" • "+esc(e.owner):""}</p>${e.fileId?`<button class="link-btn" onclick="previewFile('${escA(e.fileId)}')">Buka fail ↗</button>`:""}${e.url?` <a href="${escA(e.url)}" target="_blank" rel="noopener">Buka pautan ↗</a>`:""}</div>`);$("#results").innerHTML=h||`<div class="panel"><div class="muted">Tiada hasil untuk “${esc(q)}”.</div></div>`}
document.addEventListener("keydown",e=>{if(e.key==="Escape")closeModal()});init();
