let DATA, EVIDENCE=[], db, currentUser=null, currentProfile=null;
const DB_NAME="SKASDigitalDB",DB_VER=1,STORE="files";
const $=s=>document.querySelector(s),esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;", "'":"&#039;"}[c])),escA=s=>esc(s).replace(/`/g,"&#096;");
const icons={Dokumen:"📄",Gambar:"🖼️",Video:"🎬",Data:"📊","Lain-lain":"📎"};
const CLOUD=!!(window.SKAS_CONFIG?.SUPABASE_URL&&window.SKAS_CONFIG?.SUPABASE_KEY); let supabase=null;
if(CLOUD){
  if(!window.supabase?.createClient){
    document.addEventListener('DOMContentLoaded',()=>{
      const m=document.querySelector('#loginMsg'); if(m)m.textContent='Pustaka Supabase gagal dimuat. Cuba refresh atau pastikan CDN tidak disekat oleh rangkaian.';
    });
  }else{
    supabase=window.supabase.createClient(SKAS_CONFIG.SUPABASE_URL,SKAS_CONFIG.SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}});
  }
}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VER);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function putFile(o){return new Promise((res,rej)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).put(o);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})} function getFile(id){return new Promise((res,rej)=>{const r=db.transaction(STORE).objectStore(STORE).get(id);r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error)})} function deleteFile(id){return new Promise((res,rej)=>{const r=db.transaction(STORE,"readwrite").objectStore(STORE).delete(id);r.onsuccess=()=>res();r.onerror=()=>rej(r.error)})}
function allTargets(){const a=[];DATA.standards.forEach(s=>{if(s.direct)a.push({id:s.code,name:s.name,path:s.code});(s.aspects||[]).forEach(x=>{const hi=(x.items||[]).length>0,hsa=(x.subaspects||[]).length>0;if(!hi&&!hsa)a.push({id:x.code,name:x.name,path:`${s.code} › ${x.code} ${x.name}`});(x.items||[]).forEach(i=>a.push({id:i[0],name:i[1],path:`${s.code} › ${x.code} ${x.name}`}));(x.subaspects||[]).forEach(sa=>(sa.items||[]).forEach(i=>a.push({id:i[0],name:i[1],path:`${s.code} › ${x.code} ${x.name} › ${sa.code} ${sa.name}`})))})});return a}
function targetIds(e){return e.targetIds||[e.targetId]} function evidenceFor(id){return EVIDENCE.filter(e=>targetIds(e).includes(id))}
async function cloudLoad(){const {data,error}=await supabase.from('evidences').select('*').order('created_at',{ascending:false});if(error)throw error;EVIDENCE=(data||[]).map(row=>({id:row.id,targetIds:row.target_ids||[],targetLabel:row.target_label||'',title:row.title,category:row.category,owner:row.owner||'',date:row.evidence_date||'',url:row.url||'',note:row.note||'',filePath:row.file_path||'',fileName:row.file_name||'',fileType:row.file_type||'',fileSize:row.file_size||0,userId:row.user_id,createdAt:row.created_at}))}
async function cloudSaveEvidence(ev,file){let filePath="";if(file){filePath=`${currentUser.id}/${crypto.randomUUID()}-${file.name.replace(/[^a-zA-Z0-9._-]/g,'_')}`;const {error}=await supabase.storage.from('skas-eviden').upload(filePath,file,{contentType:file.type||'application/octet-stream',upsert:false});if(error)throw error}
const row={user_id:currentUser.id,target_ids:ev.targetIds,target_label:ev.targetLabel,title:ev.title,category:ev.category,owner:ev.owner,evidence_date:ev.date||null,url:ev.url||null,note:ev.note||null,file_path:filePath||null,file_name:file?.name||null,file_type:file?.type||null,file_size:file?.size||null};const {data,error}=await supabase.from('evidences').insert(row).select().single();if(error){if(filePath)await supabase.storage.from('skas-eviden').remove([filePath]);throw error}return data}
async function cloudFileUrl(path){const {data,error}=await supabase.storage.from('skas-eviden').createSignedUrl(path,300);if(error)throw error;return data.signedUrl}
async function cloudDeleteEvidence(e){if(e.filePath)await supabase.storage.from('skas-eviden').remove([e.filePath]);const {error}=await supabase.from('evidences').delete().eq('id',e.id);if(error)throw error}
async function getRole(){if(!CLOUD||!currentUser)return null;const {data,error}=await supabase.from('profiles').select('full_name,role').eq('id',currentUser.id).single();if(error)throw error;return data}
async function init(){try{DATA=await fetch('instrument.json').then(r=>{if(!r.ok)throw new Error('instrument.json tidak dapat dimuat ('+r.status+')');return r.json()});$('#school').textContent=SKAS_CONFIG.SCHOOL_NAME||DATA.school;await openDB();if(CLOUD && supabase){$('#modeText').textContent='☁️ Supabase Cloud';$('#localNotice').classList.add('hidden');const {data:{session}}=await supabase.auth.getSession();if(session){currentUser=session.user;await afterLogin()}else showLogin();supabase.auth.onAuthStateChange(async(_e,s)=>{if(s?.user){currentUser=s.user;setTimeout(()=>afterLogin(),0)}else{currentUser=null;currentProfile=null;EVIDENCE=[];showLogin()}})}else if(!CLOUD){currentProfile={role:'admin',full_name:'Mod Tempatan'};$('#localNotice').classList.remove('hidden');$('#appView').classList.remove('hidden');buildNav();EVIDENCE=JSON.parse(localStorage.getItem('skasEvidenceV6')||localStorage.getItem('skasEvidenceV4')||'[]');renderHome();fillTarget()}else{const m=$('#loginMsg');if(m)m.textContent='Supabase tidak dapat dimuat. Semak sambungan/CDN.'}}catch(e){const m=$('#loginMsg');if(m)m.textContent='Ralat aplikasi: '+e.message;console.error(e)}}
async function afterLogin(){try{currentProfile=await getRole();$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userPill').textContent=`👤 ${currentProfile?.full_name||currentUser.email} · ${currentProfile?.role||'guru'}`;buildNav();await cloudLoad();renderHome();fillTarget()}catch(e){console.error(e);$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');$('#loginMsg').textContent='Ralat sambungan Supabase: '+e.message}}
function showLogin(){if(CLOUD){$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden')}}
function buildNav(){let n=$('#nav');n.innerHTML='';DATA.standards.forEach(s=>{let b=document.createElement('button');b.className='nav-btn';b.innerHTML=`<span>${s.code} · ${esc(s.name)}</span><b>›</b>`;b.onclick=()=>openStandard(s.code);n.appendChild(b)});$('.home').onclick=()=>show('home')}
function show(v){$('#homeView').classList.toggle('hidden',v!=='home');$('#detailView').classList.toggle('hidden',v!=='detail');$('#resultsView').classList.toggle('hidden',v!=='results');document.querySelectorAll('.home,.nav-btn').forEach(x=>x.classList.remove('active'));if(v==='home')$('.home').classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function renderHome(){const targets=allTargets(),covered=new Set(EVIDENCE.flatMap(targetIds)).size;$('#count').textContent=EVIDENCE.length;$('#stats').innerHTML=[['Jumlah eviden',EVIDENCE.length],['Pecahan sudah ada eviden',covered],['Pecahan belum ada eviden',Math.max(0,targets.length-covered)]].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');$('#progress').innerHTML=DATA.standards.map(s=>{const ts=targets.filter(t=>t.path.startsWith(s.code+' ')||t.id===s.code),have=new Set(EVIDENCE.flatMap(targetIds).filter(id=>ts.some(t=>t.id===id))).size,pct=ts.length?Math.round(have/ts.length*100):0;return `<div class="progress"><div class="progress-head"><span>${s.code} · ${esc(s.name)}</span><b>${pct}%</b></div><div class="bar"><div class="fill" style="width:${pct}%"></div></div></div>`}).join('');const rec=[...EVIDENCE].sort((a,b)=>(b.date||b.createdAt||'').localeCompare(a.date||a.createdAt||'')).slice(0,8);$('#recent').innerHTML=rec.length?rec.map(recentHtml).join(''):`<div class="muted">Belum ada eviden. Gunakan butang “Tambah Eviden” untuk mula.</div>`}
function recentHtml(e){return `<div class="recent"><div class="ico">${icons[e.category]||'📎'}</div><div><strong>${esc(e.title)}</strong><small>${esc(e.targetLabel||targetIds(e).join(', '))} ${e.date?'• '+e.date:''}</small></div></div>`}
function openStandard(code){const s=DATA.standards.find(x=>x.code===code);if(!s)return;let body='';if(s.direct)body=`<div class="direct"><span class="tag">${s.code}</span><h2>${esc(s.name)}</h2><p class="muted">Eviden boleh direkodkan terus pada Standard 4.0. Pecahan dalaman tidak diberikan dalam struktur yang dibekalkan.</p><div class="item"><div class="item-text">📁 Eviden Standard 4.0</div><div><span class="evidence-count">${evidenceFor(s.code).length} eviden</span> <button class="add-mini" onclick="addFor('${s.code}','${escA(s.name)}')">+ Eviden</button></div></div>${renderEvidence(s.code)}</div>`;else body=(s.aspects||[]).map(a=>{const hi=(a.items||[]).length>0,hsa=(a.subaspects||[]).length>0;if(!hi&&!hsa){const c=evidenceFor(a.code).length;return `<div class="aspect-card"><div class="aspect-head"><div><b>${a.code} · ${esc(a.name)}</b><small style="display:block;margin-top:4px">Aspek</small></div><div><span class="evidence-count">${c} eviden</span> <button class="add-mini" onclick="addFor('${escA(a.code)}','${escA(a.name)}')">+ Eviden</button></div></div>${c?`<div class="evidence-list compact">${renderEvidence(a.code)}</div>`:''}</div>`}let items=(a.items||[]).map(itemHtml).join('');if(a.subaspects)items=a.subaspects.map(sa=>`<div class="aspect-card"><div class="aspect-head"><b>${sa.code} · ${esc(sa.name)}</b><small>${sa.items.length} pecahan</small></div>${sa.items.map(itemHtml).join('')}</div>`).join('');return `<div class="aspect-card"><div class="aspect-head"><b>${a.code} · ${esc(a.name)}</b><small>${a.subaspects?a.subaspects.length+' bahagian':(a.items||[]).length+' pecahan'}</small></div>${items}</div>`}).join('');$('#detail').innerHTML=`<div class="title"><div><span>${s.code}</span><h2>${esc(s.name)}</h2></div></div>${body}`;show('detail')}
function itemHtml(i){const id=i[0],cnt=evidenceFor(id).length;return `<div class="item"><div class="item-text"><span class="item-code">${id}</span>${esc(i[1])}</div><div><span class="evidence-count">${cnt} eviden</span> <button class="add-mini" onclick="addFor('${escA(id)}','${escA(i[1])}')">+ Eviden</button></div></div>${cnt?`<div class="evidence-list compact">${renderEvidence(id)}</div>`:''}`}
function renderEvidence(id){const ev=evidenceFor(id);return ev.length?ev.map(e=>`<div class="evidence-row"><strong>${icons[e.category]||'📎'} ${esc(e.title)}</strong><small>${esc(e.owner||'Tiada pemilik')} ${e.date?'• '+e.date:''}${targetIds(e).length>1?` • ${targetIds(e).length} pecahan`:''}${e.note?' • '+esc(e.note):''}</small>${e.filePath?`<button class="link-btn" onclick="previewCloudFile('${escA(e.id)}')">Buka fail ↗</button>`:''}${e.fileId?`<button class="link-btn" onclick="previewLocalFile('${escA(e.fileId)}')">Buka fail ↗</button>`:''}${e.fileName?`<small>📎 ${esc(e.fileName)}</small>`:''}${e.url?` <a href="${escA(e.url)}" target="_blank" rel="noopener">Buka pautan ↗</a>`:''}<button class="danger-link" onclick="removeEvidence('${escA(e.id)}')">Padam</button></div>`).join(''):`<div class="muted">Belum ada eviden untuk pecahan ini.</div>`}
function fillTarget(){} function fillMulti(selected=[]){$('#targets').innerHTML=allTargets().map(t=>`<label class="check"><input type="checkbox" value="${escA(t.id)}" ${selected.includes(t.id)?'checked':''}> <span>${esc(t.id)} — ${esc(t.name)}</span></label>`).join('')}
function addFor(id,label){openModal(id,label)}function openModal(id='',label=''){$('#modal').classList.remove('hidden');$('#form').reset();fillMulti(id?[id]:[]);$('#fileInfo').textContent='Tiada fail dipilih.'}function closeModal(){$('#modal').classList.add('hidden')}
$('#addBtn').onclick=()=>openModal();$('#close').onclick=closeModal;$('#cancel').onclick=closeModal;$('#file').onchange=e=>{$('#fileInfo').textContent=e.target.files[0]?`${e.target.files[0].name} • ${formatBytes(e.target.files[0].size)}`:'Tiada fail dipilih.'};
$('#form').onsubmit=async e=>{e.preventDefault();const f=e.target,targets=[...f.querySelectorAll('#targets input:checked')].map(x=>x.value);if(!targets.length)return alert('Pilih sekurang-kurangnya satu pecahan instrumen.');const file=f.file.files[0];const labels=targets.map(id=>allTargets().find(t=>t.id===id)).filter(Boolean);const ev={targetIds:targets,targetLabel:labels.map(x=>x.id).join(', '),title:f.title.value.trim(),category:f.category.value,owner:f.owner.value.trim(),date:f.date.value,url:f.url.value.trim(),note:f.note.value.trim()};try{if(CLOUD){await cloudSaveEvidence(ev,file);await cloudLoad()}else{let fileId='';if(file){fileId='f_'+Date.now()+'_'+Math.random().toString(36).slice(2);await putFile({id:fileId,name:file.name,type:file.type,size:file.size,blob:file})}EVIDENCE.push({...ev,id:Date.now().toString(),fileId});localStorage.setItem('skasEvidenceV6',JSON.stringify(EVIDENCE))}closeModal();renderHome();show('home')}catch(err){alert('Gagal menyimpan eviden: '+err.message)}};
async function previewCloudFile(id){try{const e=EVIDENCE.find(x=>x.id===id);if(!e?.filePath)return;const url=await cloudFileUrl(e.filePath);window.open(url,'_blank')}catch(err){alert('Fail tidak dapat dibuka: '+err.message)}}
async function previewLocalFile(id){const f=await getFile(id);if(!f)return alert('Fail tidak ditemui.');const u=URL.createObjectURL(f.blob);window.open(u,'_blank')}
async function removeEvidence(id){const e=EVIDENCE.find(x=>x.id===id);if(!e||!confirm(`Padam eviden “${e.title}”?`))return;try{if(CLOUD){await cloudDeleteEvidence(e);await cloudLoad()}else{if(e.fileId)await deleteFile(e.fileId);EVIDENCE=EVIDENCE.filter(x=>x.id!==id);localStorage.setItem('skasEvidenceV6',JSON.stringify(EVIDENCE))}renderHome();if(!$('#detailView').classList.contains('hidden')){const first=targetIds(e)[0],s=DATA.standards.find(s=>s.code===first||first.startsWith(s.code+'.'));if(s)openStandard(s.code)}}catch(err){alert('Gagal memadam: '+err.message)}}
function formatBytes(n){if(n<1024)return n+' B';if(n<1048576)return (n/1024).toFixed(1)+' KB';return (n/1048576).toFixed(1)+' MB'}
$('#back').onclick=()=>show('home');$('#clear').onclick=()=>{$('#search').value='';doSearch('')};$('#search').oninput=e=>doSearch(e.target.value);
function doSearch(q){q=q.trim().toLowerCase();if(!q)return show('home');show('results');const targets=allTargets(),matches=targets.filter(t=>`${t.id} ${t.name} ${t.path}`.toLowerCase().includes(q)),ev=EVIDENCE.filter(e=>`${e.title} ${e.targetLabel} ${e.owner} ${e.note}`.toLowerCase().includes(q));let h='';matches.forEach(t=>h+=`<div class="result"><span class="tag">${esc(t.id)}</span><h3>${esc(t.name)}</h3><p>${esc(t.path)} • ${evidenceFor(t.id).length} eviden</p><button onclick="addFor('${escA(t.id)}','${escA(t.name)}')">+ Tambah eviden</button></div>`);ev.forEach(e=>h+=`<div class="result"><span class="tag">${esc(e.category)}</span><h3>${esc(e.title)}</h3><p>${esc(e.targetLabel)}${e.owner?' • '+esc(e.owner):''}</p>${e.filePath?`<button class="link-btn" onclick="previewCloudFile('${escA(e.id)}')">Buka fail ↗</button>`:''}${e.fileId?`<button class="link-btn" onclick="previewLocalFile('${escA(e.fileId)}')">Buka fail ↗</button>`:''}${e.url?` <a href="${escA(e.url)}" target="_blank" rel="noopener">Buka pautan ↗</a>`:''}</div>`);$('#results').innerHTML=h||`<div class="panel"><div class="muted">Tiada hasil untuk “${esc(q)}”.</div></div>`}
function exportEvidence(){const payload={version:2,mode:CLOUD?'supabase':'local',exportedAt:new Date().toISOString(),evidence:EVIDENCE};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SKAS-eviden-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();URL.revokeObjectURL(a.href)}
async function importEvidenceFile(file){try{const obj=JSON.parse(await file.text()),incoming=Array.isArray(obj)?obj:obj.evidence;if(!Array.isArray(incoming))throw new Error('Format backup tidak sah');if(!confirm(`Import ${incoming.length} rekod eviden?`))return;if(CLOUD){let ok=0;for(const e of incoming){const row={user_id:currentUser.id,target_ids:e.targetIds||[e.targetId],target_label:e.targetLabel||'',title:e.title,category:e.category||'Lain-lain',owner:e.owner||'',evidence_date:e.date||null,url:e.url||null,note:e.note||null,file_path:null};const {error}=await supabase.from('evidences').insert(row);if(!error)ok++}await cloudLoad();alert(`${ok} eviden berjaya diimport. Fail tempatan daripada backup lama tidak diupload.`)}else{const existing=new Set(EVIDENCE.map(e=>e.id));let added=0;incoming.forEach(e=>{if(e?.id&&!existing.has(e.id)){EVIDENCE.push(e);added++}});localStorage.setItem('skasEvidenceV6',JSON.stringify(EVIDENCE));renderHome();alert(`${added} eviden berjaya diimport.`)}}catch(err){alert('Backup tidak dapat diimport: '+err.message)}}
function openImport(){const i=document.createElement('input');i.type='file';i.accept='application/json,.json';i.onchange=()=>i.files[0]&&importEvidenceFile(i.files[0]);i.click()}
$('#loginForm').onsubmit=async e=>{e.preventDefault();if(!CLOUD)return;$('#loginMsg').textContent='Sedang log masuk...';const {error}=await supabase.auth.signInWithPassword({email:$('#loginEmail').value.trim(),password:$('#loginPassword').value});$('#loginMsg').textContent=error?error.message:'Berjaya.'};
$('#signupBtn').onclick=async()=>{if(!CLOUD)return;const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value;if(!email||!password)return $('#loginMsg').textContent='Isi email dan kata laluan dahulu.';const {error}=await supabase.auth.signUp({email,password,options:{data:{full_name:email.split('@')[0]}}});$('#loginMsg').textContent=error?error.message:'Akaun didaftarkan. Semak email jika pengesahan email diaktifkan.'};
$('#resetBtn').onclick=async()=>{if(!CLOUD)return;const email=$('#loginEmail').value.trim();if(!email)return $('#loginMsg').textContent='Masukkan email dahulu.';const {error}=await supabase.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});$('#loginMsg').textContent=error?error.message:'Pautan tetapan semula telah dihantar jika email itu berdaftar.'};
$('#logoutBtn').onclick=async()=>{if(CLOUD)await supabase.auth.signOut()};
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});init();
