let DATA,EVIDENCE=[],db,currentUser=null,currentProfile=null,editingId=null;
const DB_NAME="SKASDigitalDB",DB_VER=1,STORE="files";
const $=s=>document.querySelector(s);
const esc=s=>String(s??"").replace(/[&<>"']/g,c=>({"&":"&amp;","<":"&lt;",">":"&gt;",'"':"&quot;","'":"&#039;"}[c]));
const escA=s=>esc(s).replace(/`/g,"&#096;");
const icons={Dokumen:"📄",Gambar:"🖼️",Video:"🎬",Data:"📊","Lain-lain":"📎"};
const CLOUD=!!(window.SKAS_CONFIG?.SUPABASE_URL&&window.SKAS_CONFIG?.SUPABASE_KEY);let sb=null;
if(CLOUD&&window.supabase?.createClient){sb=window.supabase.createClient(SKAS_CONFIG.SUPABASE_URL,SKAS_CONFIG.SUPABASE_KEY,{auth:{persistSession:true,autoRefreshToken:true,detectSessionInUrl:true}})}
function openDB(){return new Promise((res,rej)=>{const r=indexedDB.open(DB_NAME,DB_VER);r.onupgradeneeded=()=>{if(!r.result.objectStoreNames.contains(STORE))r.result.createObjectStore(STORE,{keyPath:"id"})};r.onsuccess=()=>{db=r.result;res(db)};r.onerror=()=>rej(r.error)})}
function allTargets(){const a=[];DATA.standards.forEach(s=>{if(s.direct)a.push({id:s.code,name:s.name,path:s.code});(s.aspects||[]).forEach(x=>{const hi=(x.items||[]).length>0,hsa=(x.subaspects||[]).length>0;if(!hi&&!hsa)a.push({id:x.code,name:x.name,path:`${s.code} › ${x.code} ${x.name}`});(x.items||[]).forEach(i=>a.push({id:i[0],name:i[1],path:`${s.code} › ${x.code} ${x.name}`}));(x.subaspects||[]).forEach(sa=>(sa.items||[]).forEach(i=>a.push({id:i[0],name:i[1],path:`${s.code} › ${x.code} ${x.name} › ${sa.code} ${sa.name}`})))})});return a}
function targetIds(e){return e.targetIds||[e.targetId]}
function evidenceFor(id){return EVIDENCE.filter(e=>targetIds(e).includes(id))}
function canEdit(e){return !CLOUD||e.userId===currentUser?.id||['admin','nazir'].includes(currentProfile?.role)}
function canDelete(e){return canEdit(e)}
async function cloudLoad(){const {data,error}=await sb.from('evidences').select('*').order('created_at',{ascending:false});if(error)throw error;EVIDENCE=(data||[]).map(row=>({id:row.id,targetIds:row.target_ids||[],targetLabel:row.target_label||'',title:row.title,category:row.category,owner:row.owner||'',date:row.evidence_date||'',url:row.url||'',note:row.note||'',userId:row.user_id,createdAt:row.created_at,updatedAt:row.updated_at}))}
async function cloudInsert(ev){const row={user_id:currentUser.id,target_ids:ev.targetIds,target_label:ev.targetLabel,title:ev.title,category:ev.category,owner:ev.owner,evidence_date:ev.date||null,url:ev.url||null,note:ev.note||null};const {data,error}=await sb.from('evidences').insert(row).select().single();if(error)throw error;return data}
async function cloudUpdate(id,ev){const row={target_ids:ev.targetIds,target_label:ev.targetLabel,title:ev.title,category:ev.category,owner:ev.owner,evidence_date:ev.date||null,url:ev.url||null,note:ev.note||null,updated_at:new Date().toISOString()};const {data,error}=await sb.from('evidences').update(row).eq('id',id).select().single();if(error)throw error;return data}
async function cloudDelete(id){const {error}=await sb.from('evidences').delete().eq('id',id);if(error)throw error}
async function getRole(){if(!CLOUD||!currentUser)return null;const {data,error}=await sb.from('profiles').select('full_name,role').eq('id',currentUser.id).single();if(error)throw error;return data}
async function init(){try{DATA=await fetch('instrument.json').then(r=>{if(!r.ok)throw new Error('instrument.json tidak dapat dimuat ('+r.status+')');return r.json()});$('#school').textContent=SKAS_CONFIG.SCHOOL_NAME||DATA.school;await openDB();if(CLOUD&&sb){$('#modeText').textContent='☁️ Supabase Cloud';const {data:{session}}=await sb.auth.getSession();if(session){currentUser=session.user;await afterLogin()}else showLogin();sb.auth.onAuthStateChange(async(_e,s)=>{if(s?.user){currentUser=s.user;setTimeout(()=>afterLogin(),0)}else{currentUser=null;currentProfile=null;EVIDENCE=[];showLogin()}})}else{currentProfile={role:'admin',full_name:'Mod Tempatan'};$('#localNotice').classList.remove('hidden');$('#appView').classList.remove('hidden');buildNav();EVIDENCE=JSON.parse(localStorage.getItem('skasEvidenceV6')||localStorage.getItem('skasEvidenceV4')||'[]');renderHome()}}catch(e){const m=$('#loginMsg');if(m)m.textContent='Ralat aplikasi: '+e.message;console.error(e)}}
async function afterLogin(){try{currentProfile=await getRole();$('#loginView').classList.add('hidden');$('#appView').classList.remove('hidden');$('#userPill').textContent=`👤 ${currentProfile?.full_name||currentUser.email} · ${currentProfile?.role||'guru'}`;buildNav();await cloudLoad();renderHome()}catch(e){console.error(e);$('#loginView').classList.remove('hidden');$('#appView').classList.add('hidden');$('#loginMsg').textContent='Ralat sambungan Supabase: '+e.message}}
function showLogin(){if(CLOUD){$('#appView').classList.add('hidden');$('#loginView').classList.remove('hidden')}}
function buildNav(){const n=$('#nav');n.innerHTML='';DATA.standards.forEach(s=>{const b=document.createElement('button');b.className='nav-btn';b.innerHTML=`<span>${s.code} · ${esc(s.name)}</span><b>›</b>`;b.onclick=()=>openStandard(s.code);n.appendChild(b)});$('.home').onclick=()=>show('home');const un=$('#usersNav');if(un){un.classList.toggle('hidden',currentProfile?.role!=='admin');un.onclick=()=>openUsers()}}
function show(v){['homeView','detailView','resultsView','usersView'].forEach(id=>$('#'+id)?.classList.toggle('hidden',id!==v+'View'));document.querySelectorAll('.home,.nav-btn').forEach(x=>x.classList.remove('active'));if(v==='home')$('.home').classList.add('active');if(v==='users')$('#usersNav')?.classList.add('active');window.scrollTo({top:0,behavior:'smooth'})}
function renderHome(){const targets=allTargets(),covered=new Set(EVIDENCE.flatMap(targetIds)).size;$('#count').textContent=EVIDENCE.length;$('#stats').innerHTML=[['Jumlah eviden',EVIDENCE.length],['Pecahan sudah ada eviden',covered],['Pecahan belum ada eviden',Math.max(0,targets.length-covered)]].map(x=>`<div class="stat"><small>${x[0]}</small><strong>${x[1]}</strong></div>`).join('');$('#progress').innerHTML=DATA.standards.map(s=>{const ts=targets.filter(t=>t.path.startsWith(s.code+' ')||t.id===s.code),have=new Set(EVIDENCE.flatMap(targetIds).filter(id=>ts.some(t=>t.id===id))).size,pct=ts.length?Math.round(have/ts.length*100):0;return `<div class="progress"><div class="progress-head"><span>${s.code} · ${esc(s.name)}</span><b>${pct}%</b></div><div class="bar"><div class="fill" style="width:${pct}%"></div></div></div>`}).join('');const rec=[...EVIDENCE].sort((a,b)=>(b.date||b.createdAt||'').localeCompare(a.date||a.createdAt||'')).slice(0,8);$('#recent').innerHTML=rec.length?rec.map(recentHtml).join(''):`<div class="muted">Belum ada eviden. Gunakan butang “Tambah Eviden” untuk mula.</div>`}
function recentHtml(e){return `<div class="recent"><div class="ico">${icons[e.category]||'📎'}</div><div><strong>${esc(e.title)}</strong><small>${esc(e.targetLabel||targetIds(e).join(', '))} ${e.date?'• '+e.date:''}</small></div></div>`}
function openStandard(code){const s=DATA.standards.find(x=>x.code===code);if(!s)return;let body='';if(s.direct)body=`<div class="direct"><span class="tag">${s.code}</span><h2>${esc(s.name)}</h2><p class="muted">Eviden boleh direkodkan terus pada Standard 4.0. Pecahan dalaman tidak diberikan dalam struktur yang dibekalkan.</p><div class="item"><div class="item-text">📁 Eviden Standard 4.0</div><div><span class="evidence-count">${evidenceFor(s.code).length} eviden</span> <button class="add-mini" onclick="addFor('${escA(s.code)}','${escA(s.name)}')">+ Eviden</button></div></div>${renderEvidence(s.code)}</div>`;else body=(s.aspects||[]).map(a=>{const hi=(a.items||[]).length>0,hsa=(a.subaspects||[]).length>0;if(!hi&&!hsa){const c=evidenceFor(a.code).length;return `<div class="aspect-card"><div class="aspect-head"><div><b>${a.code} · ${esc(a.name)}</b><small style="display:block;margin-top:4px">Aspek</small></div><div><span class="evidence-count">${c} eviden</span> <button class="add-mini" onclick="addFor('${escA(a.code)}','${escA(a.name)}')">+ Eviden</button></div></div>${c?`<div class="evidence-list compact">${renderEvidence(a.code)}</div>`:''}</div>`}let items=(a.items||[]).map(itemHtml).join('');if(a.subaspects)items=a.subaspects.map(sa=>`<div class="aspect-card"><div class="aspect-head"><b>${sa.code} · ${esc(sa.name)}</b><small>${sa.items.length} pecahan</small></div>${sa.items.map(itemHtml).join('')}</div>`).join('');return `<div class="aspect-card"><div class="aspect-head"><b>${a.code} · ${esc(a.name)}</b><small>${a.subaspects?a.subaspects.length+' bahagian':(a.items||[]).length+' pecahan'}</small></div>${items}</div>`}).join('');$('#detail').innerHTML=`<div class="title"><div><span>${s.code}</span><h2>${esc(s.name)}</h2></div></div>${body}`;show('detail')}
function itemHtml(i){const id=i[0],cnt=evidenceFor(id).length;return `<div class="item"><div class="item-text"><span class="item-code">${id}</span>${esc(i[1])}</div><div><span class="evidence-count">${cnt} eviden</span> <button class="add-mini" onclick="addFor('${escA(id)}','${escA(i[1])}')">+ Eviden</button></div></div>${cnt?`<div class="evidence-list compact">${renderEvidence(id)}</div>`:''}`}
function evidenceActions(e){let h='';if(e.url)h+=`<a class="action-link" href="${escA(e.url)}" target="_blank" rel="noopener">Buka pautan ↗</a>`;if(canEdit(e))h+=`<button class="link-btn action-btn" onclick="editEvidence('${escA(e.id)}')">✏️ Edit</button>`;if(canDelete(e))h+=`<button class="danger-link action-btn" onclick="removeEvidence('${escA(e.id)}')">🗑️ Padam</button>`;return h}
function renderEvidence(id){const ev=evidenceFor(id);return ev.length?ev.map(e=>`<div class="evidence-row"><strong>${icons[e.category]||'📎'} ${esc(e.title)}</strong><small>${esc(e.owner||'Tiada pemilik')} ${e.date?'• '+e.date:''}${targetIds(e).length>1?` • ${targetIds(e).length} pecahan`:''}${e.note?' • '+esc(e.note):''}</small><div class="evidence-actions">${evidenceActions(e)}</div></div>`).join(''):`<div class="muted">Belum ada eviden untuk pecahan ini.</div>`}
function fillMulti(selected=[]){$('#targets').innerHTML=allTargets().map(t=>`<label class="check"><input type="checkbox" value="${escA(t.id)}" ${selected.includes(t.id)?'checked':''}> <span>${esc(t.id)} — ${esc(t.name)}</span></label>`).join('')}
function addFor(id,label){openModal(id,label)}
function openModal(id='',label='',ev=null){editingId=ev?.id||null;$('#modal').classList.remove('hidden');$('#form').reset();$('#modalTitle').textContent=editingId?'Edit Eviden':'Tambah Eviden';$('#modalTag').textContent=editingId?'EDIT EVIDEN':'EVIDEN';$('#saveBtn').textContent=editingId?'Simpan Perubahan':'Simpan Eviden';fillMulti(ev?targetIds(ev):(id?[id]:[]));if(ev){const f=$('#form');f.title.value=ev.title||'';f.category.value=ev.category||'Dokumen';f.owner.value=ev.owner||'';f.date.value=ev.date||'';f.url.value=ev.url||'';f.note.value=ev.note||''}}
function closeModal(){editingId=null;$('#modal').classList.add('hidden')}
async function saveEvidence(ev){if(CLOUD){if(editingId)await cloudUpdate(editingId,ev);else await cloudInsert(ev);await cloudLoad()}else{if(editingId){const i=EVIDENCE.findIndex(x=>x.id===editingId);if(i>=0)EVIDENCE[i]={...EVIDENCE[i],...ev,updatedAt:new Date().toISOString()}}else EVIDENCE.unshift({...ev,id:Date.now().toString(),userId:'local'});localStorage.setItem('skasEvidenceV6',JSON.stringify(EVIDENCE))}}
async function removeEvidence(id){const ev=EVIDENCE.find(x=>x.id===id);if(!ev||!canDelete(ev))return alert('Anda tidak mempunyai kebenaran untuk memadam eviden ini.');if(!confirm(`Padam eviden “${ev.title}”?\n\nRekod dalam Supabase akan dipadam. Fail Google Drive tidak dipadam.`))return;try{if(CLOUD){await cloudDelete(id);await cloudLoad()}else{EVIDENCE=EVIDENCE.filter(x=>x.id!==id);localStorage.setItem('skasEvidenceV6',JSON.stringify(EVIDENCE))}renderHome();const active=document.querySelector('#detailView:not(.hidden)');if(active){const code=document.querySelector('#detail .title span')?.textContent?.trim();if(code)openStandard(code)}}catch(err){alert('Gagal memadam eviden: '+err.message)}}
async function editEvidence(id){const ev=EVIDENCE.find(x=>x.id===id);if(!ev||!canEdit(ev))return alert('Anda tidak mempunyai kebenaran untuk mengubah eviden ini.');openModal('', '', ev)}
$('#addBtn').onclick=()=>openModal();$('#close').onclick=closeModal;$('#cancel').onclick=closeModal;
$('#form').onsubmit=async e=>{e.preventDefault();const f=e.target,targets=[...f.querySelectorAll('#targets input:checked')].map(x=>x.value);if(!targets.length)return alert('Pilih sekurang-kurangnya satu pecahan instrumen.');const labels=targets.map(id=>allTargets().find(t=>t.id===id)).filter(Boolean);const url=f.url.value.trim();if(!url)return alert('Masukkan pautan Google Drive/Google Docs bagi eviden ini.');try{const u=new URL(url);if(!['http:','https:'].includes(u.protocol))throw 0}catch(_){return alert('Pautan tidak sah. Sila masukkan URL lengkap.')}const ev={targetIds:targets,targetLabel:labels.map(x=>x.id).join(', '),title:f.title.value.trim(),category:f.category.value,owner:f.owner.value.trim(),date:f.date.value,url,note:f.note.value.trim()};if(!ev.title)return alert('Nama eviden diperlukan.');try{await saveEvidence(ev);closeModal();renderHome();show('home');alert(editingId?'Eviden berjaya dikemas kini.':'Eviden berjaya disimpan.')}catch(err){alert('Gagal menyimpan eviden: '+err.message)}};
$('#back').onclick=()=>show('home');$('#clear').onclick=()=>{$('#search').value='';doSearch('')};$('#search').oninput=e=>doSearch(e.target.value);
function doSearch(q){q=q.trim().toLowerCase();if(!q)return show('home');show('results');const targets=allTargets(),matches=targets.filter(t=>`${t.id} ${t.name} ${t.path}`.toLowerCase().includes(q)),ev=EVIDENCE.filter(e=>`${e.title} ${e.targetLabel} ${e.owner} ${e.note} ${e.category}`.toLowerCase().includes(q));let h='';matches.forEach(t=>h+=`<div class="result"><span class="tag">${esc(t.id)}</span><h3>${esc(t.name)}</h3><p>${esc(t.path)} • ${evidenceFor(t.id).length} eviden</p><button onclick="addFor('${escA(t.id)}','${escA(t.name)}')">+ Tambah eviden</button></div>`);ev.forEach(e=>h+=`<div class="result"><span class="tag">${esc(e.category)}</span><h3>${esc(e.title)}</h3><p>${esc(e.targetLabel)}${e.owner?' • '+esc(e.owner):''}${e.date?' • '+esc(e.date):''}</p><div class="evidence-actions">${evidenceActions(e)}</div></div>`);$('#results').innerHTML=h||`<div class="panel"><div class="muted">Tiada hasil untuk “${esc(q)}”.</div></div>`}
async function cloudUsers(){const {data,error}=await sb.from('profiles').select('id,full_name,role,email,created_at').order('created_at',{ascending:true});if(error)throw error;return data||[]}
function openUsers(){if(currentProfile?.role!=='admin')return alert('Akses Pengurusan Pengguna hanya untuk Admin.');show('users');loadUsers()}
async function loadUsers(){const box=$('#usersTable');if(!box)return;box.innerHTML='<div class=\"muted\">Memuatkan pengguna...</div>';try{const users=await cloudUsers();if(!users.length){box.innerHTML='<div class=\"muted\">Tiada pengguna.</div>';return}box.innerHTML=`<div style=\"overflow:auto\"><table class=\"users-table\"><thead><tr><th>Pengguna</th><th>Role</th><th>Didaftar</th><th>Tindakan</th></tr></thead><tbody>${users.map(u=>`<tr><td><span class=\"user-name\">${esc(u.full_name||'Tanpa nama')}</span><span class=\"user-email\">${esc(u.email||'Email belum disegerakkan')}</span><span class=\"user-id\">${esc(u.id)}</span></td><td><select class=\"role-select\" data-role-id=\"${escA(u.id)}\" ${u.id===currentUser.id?'disabled':''}><option value=\"guru\" ${u.role==='guru'?'selected':''}>Guru</option><option value=\"nazir\" ${u.role==='nazir'?'selected':''}>Nazir</option><option value=\"admin\" ${u.role==='admin'?'selected':''}>Admin</option></select></td><td>${esc(u.created_at?new Date(u.created_at).toLocaleDateString('ms-MY'):'—')}</td><td><button class=\"link-btn\" onclick=\"editProfile('${escA(u.id)}')\">✏️ Nama</button><button class=\"primary\" style=\"padding:6px 9px;font-size:9px\" onclick=\"saveUserRole('${escA(u.id)}')\">Simpan</button></td></tr>`).join('')}</tbody></table></div><p class=\"muted\">Untuk menambah akaun login baharu, gunakan butang “＋ Tambah Pengguna”. V7.9 tidak menyimpan Secret/Service Role Key dalam GitHub.</p>`}catch(e){box.innerHTML=`<div class=\"panel\"><b>Pengurusan pengguna belum boleh dimuatkan.</b><p class=\"muted\">Pastikan migrasi V7.9 dalam <b>schema-users.sql</b> sudah dijalankan di Supabase. Ralat: ${esc(e.message)}</p></div>`}}
async function saveUserRole(id){if(currentProfile?.role!=='admin')return; if(id===currentUser.id)return alert('Role akaun Admin semasa tidak diubah untuk mengelakkan anda terkunci keluar.');const sel=document.querySelector(`[data-role-id=\"${CSS.escape(id)}\"]`);if(!sel)return;try{const {error}=await sb.from('profiles').update({role:sel.value}).eq('id',id);if(error)throw error;await loadUsers();alert('Role pengguna berjaya dikemas kini.')}catch(e){alert('Gagal mengemas kini role: '+e.message)}}
async function editProfile(id){if(currentProfile?.role!=='admin')return;const users=await cloudUsers();const u=users.find(x=>x.id===id);if(!u)return;const name=prompt('Nama pengguna:',u.full_name||'');if(name===null)return;const clean=name.trim();if(!clean)return alert('Nama tidak boleh kosong.');try{const {error}=await sb.from('profiles').update({full_name:clean}).eq('id',id);if(error)throw error;if(id===currentUser.id){currentProfile.full_name=clean;$('#userPill').textContent=`👤 ${clean} · ${currentProfile.role}`}await loadUsers()}catch(e){alert('Gagal mengemas kini nama: '+e.message)}}
function exportEvidence(){const payload={version:4,storage:'Google Drive',mode:CLOUD?'supabase':'local',exportedAt:new Date().toISOString(),evidence:EVIDENCE};const blob=new Blob([JSON.stringify(payload,null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download='SKAS-eviden-backup-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(a.href),1000)}
async function importEvidenceFile(file){try{const obj=JSON.parse(await file.text()),incoming=Array.isArray(obj)?obj:obj.evidence;if(!Array.isArray(incoming))throw new Error('Format backup tidak sah');if(!confirm(`Import ${incoming.length} rekod eviden?`))return;if(CLOUD){let ok=0;for(const e of incoming){const row={user_id:currentUser.id,target_ids:e.targetIds||[e.targetId],target_label:e.targetLabel||'',title:e.title,category:e.category||'Lain-lain',owner:e.owner||'',evidence_date:e.date||null,url:e.url||null,note:e.note||null};const {error}=await sb.from('evidences').insert(row);if(!error)ok++}await cloudLoad();alert(`${ok} eviden berjaya diimport.`)}else{const existing=new Set(EVIDENCE.map(e=>e.id));let added=0;incoming.forEach(e=>{if(e?.id&&!existing.has(e.id)){EVIDENCE.push(e);added++}});localStorage.setItem('skasEvidenceV6',JSON.stringify(EVIDENCE));renderHome();alert(`${added} eviden berjaya diimport.`)}}catch(err){alert('Backup tidak dapat diimport: '+err.message)}}
function openImport(){const i=document.createElement('input');i.type='file';i.accept='application/json,.json';i.onchange=()=>i.files[0]&&importEvidenceFile(i.files[0]);i.click()}
async function showConnectionDiagnostic(){const m=$('#loginMsg');m.textContent='Menguji sambungan Supabase...';try{const r=await fetch(SKAS_CONFIG.SUPABASE_URL+'/auth/v1/settings',{headers:{apikey:SKAS_CONFIG.SUPABASE_KEY}});const t=await r.text();m.innerHTML='Sambungan HTTP: '+r.status+' '+(r.ok?'OK':'GAGAL')+'<br><small>'+esc(t.slice(0,500))+'</small>'}catch(err){m.innerHTML='Ujian sambungan gagal: '+esc(err?.message||String(err))}}
window.testSupabaseConnection=showConnectionDiagnostic;
$('#loginForm').onsubmit=async e=>{e.preventDefault();if(!CLOUD)return;const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value;$('#loginMsg').innerHTML='Sedang log masuk...';try{const {error}=await sb.auth.signInWithPassword({email,password});if(error){$('#loginMsg').innerHTML='Supabase: '+esc(error.message)+(error.status?' (HTTP '+error.status+')':'')+'<br><button type="button" class="link-btn" onclick="testSupabaseConnection()">Uji sambungan</button>';return}$('#loginMsg').textContent='Berjaya. Memuatkan dashboard...'}catch(err){$('#loginMsg').innerHTML='Tidak dapat menghubungi Supabase.<br><small>Ralat: '+esc(err?.message||String(err))+'</small><br><button type="button" class="link-btn" onclick="testSupabaseConnection()">Uji sambungan</button>'}};
$('#signupBtn').onclick=async()=>{if(!CLOUD)return;const email=$('#loginEmail').value.trim(),password=$('#loginPassword').value;if(!email||!password)return $('#loginMsg').textContent='Isi email dan kata laluan dahulu.';const {error}=await sb.auth.signUp({email,password,options:{data:{full_name:email.split('@')[0]}}});$('#loginMsg').textContent=error?error.message:'Akaun didaftarkan. Semak email jika pengesahan email diaktifkan.'};
$('#resetBtn').onclick=async()=>{if(!CLOUD)return;const email=$('#loginEmail').value.trim();if(!email)return $('#loginMsg').textContent='Masukkan email dahulu.';const {error}=await sb.auth.resetPasswordForEmail(email,{redirectTo:location.origin+location.pathname});$('#loginMsg').textContent=error?error.message:'Pautan tetapan semula telah dihantar jika email itu berdaftar.'};
$('#userHelpBtn').onclick=()=>$('#userModal').classList.remove('hidden');$('#userClose').onclick=()=>$('#userModal').classList.add('hidden');$('#userCancel').onclick=()=>$('#userModal').classList.add('hidden');$('#refreshUsersBtn').onclick=()=>loadUsers();$('#logoutBtn').onclick=async()=>{if(CLOUD)await sb.auth.signOut()};
document.addEventListener('keydown',e=>{if(e.key==='Escape')closeModal()});
init();
